"use server";

import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { signFathomPayload, type FathomWebhookPayload } from "@/lib/fathom";
import { processFathomWebhook } from "@/lib/fathom-webhook";
import { STAGE_DEFAULT_PROBABILITY, OPEN_STAGES } from "@/lib/crm";

/** Builds a realistic-shaped Fathom payload for the "Fire a test event"
 *  button — same fields the real webhook reads, just synthetic content. */
function buildTestPayload(attendeeEmail: string, attendeeName: string): FathomWebhookPayload {
  const now = new Date().toISOString();
  return {
    type: "recording.completed",
    recording_id: `test-${Date.now()}`,
    url: "https://fathom.video/calls/test-recording",
    recording_start_time: now,
    calendar_invitees: [
      { name: "Sales rep", email: "rep@example.invalid", is_external: false },
      { name: attendeeName, email: attendeeEmail, is_external: true },
    ],
    recorded_by: { email: "rep@example.invalid" },
    default_summary: {
      markdown_formatted:
        "**Test call** — synthetic AI summary generated by the \"Fire a test event\" button, not a real Fathom recording.",
    },
    transcript: [
      { speaker_name: "Sales rep", text: "Hey, thanks for hopping on the call today." },
      { speaker_name: attendeeName, text: "Of course — excited to learn more." },
    ],
  };
}

/** Fires a synthetic Fathom event through the real signature-verification
 *  and matching path — no real recording needed to check the integration
 *  works. Pass a leadId to test the matched path (using that lead's real
 *  email); omit it to deliberately test the Unmatched calls path. */
export async function fireFathomTestEvent(leadId?: string) {
  const signingKey = process.env.FATHOM_WEBHOOK_SIGNING_KEY;
  if (!signingKey) {
    throw new Error("FATHOM_WEBHOOK_SIGNING_KEY isn't configured on the server yet — nothing to test against.");
  }

  let attendeeEmail = `test-unmatched-${Date.now()}@example.invalid`;
  let attendeeName = "Test Prospect";
  if (leadId) {
    const lead = await db.lead.findUnique({ where: { id: leadId } });
    if (!lead) throw new Error("Lead not found");
    if (!lead.email) {
      throw new Error(`${lead.name} has no email on file — pick a lead with an email to test the matched path.`);
    }
    attendeeEmail = lead.email;
    attendeeName = lead.name;
  }

  const payload = buildTestPayload(attendeeEmail, attendeeName);
  const rawBody = JSON.stringify(payload);
  const headers = signFathomPayload(rawBody, signingKey);
  const result = await processFathomWebhook(rawBody, headers, { isTest: true });

  revalidatePath("/sales/crm/webhooks");
  revalidatePath("/sales/crm/unmatched");
  revalidatePath("/sales/crm");
  if (leadId) revalidatePath(`/sales/crm/${leadId}`);

  return { status: result.status, ...result.body };
}

/** Turns an UnmatchedCall into a real SalesCall on the chosen lead — the
 *  "assign it to a lead in one click" half of "never silently drop a
 *  call." Mirrors the Fathom webhook's own matched-call logic exactly. */
export async function assignUnmatchedCall(unmatchedId: string, leadId: string) {
  const unmatched = await db.unmatchedCall.findUnique({ where: { id: unmatchedId } });
  if (!unmatched) throw new Error("Unmatched call not found");
  const lead = await db.lead.findUnique({ where: { id: leadId } });
  if (!lead) throw new Error("Lead not found");

  const scheduledAt = unmatched.scheduledAt ?? new Date().toISOString().slice(0, 10);

  await db.$transaction(async (tx) => {
    const existingCall = unmatched.fathomRecordingId
      ? await tx.salesCall.findUnique({ where: { fathomRecordingId: unmatched.fathomRecordingId } })
      : null;

    if (existingCall) {
      await tx.salesCall.update({
        where: { id: existingCall.id },
        data: {
          leadId,
          recordingLink: unmatched.recordingLink,
          aiSummary: unmatched.aiSummary,
          transcript: unmatched.transcript,
          scheduledAt,
          startedAt: unmatched.startedAt,
        },
      });
    } else {
      await tx.salesCall.create({
        data: {
          leadId,
          scheduledAt,
          callStatus: "showed",
          result: null,
          recordingLink: unmatched.recordingLink,
          aiSummary: unmatched.aiSummary,
          transcript: unmatched.transcript,
          startedAt: unmatched.startedAt,
          fathomRecordingId: unmatched.fathomRecordingId,
        },
      });
    }

    if (OPEN_STAGES.has(lead.stage)) {
      await tx.lead.update({
        where: { id: leadId },
        data: {
          stage: "showed",
          stageProbability: STAGE_DEFAULT_PROBABILITY.showed,
          stageChangedAt: new Date(),
          nextCallAt: null,
        },
      });
    }

    await tx.unmatchedCall.delete({ where: { id: unmatchedId } });
  });

  revalidatePath("/sales/crm/unmatched");
  revalidatePath("/sales/crm");
  revalidatePath(`/sales/crm/${leadId}`);
}

/** Discards an unmatched event that isn't a real sales call (an internal
 *  test, a mis-fired recording) — the explicit alternative to assigning
 *  it, so the list doesn't just accumulate noise with no way to clear it. */
export async function dismissUnmatchedCall(id: string) {
  await db.unmatchedCall.delete({ where: { id } });
  revalidatePath("/sales/crm/unmatched");
}
